### PR TITLE
All the latest 2D stuff

### PR DESCRIPTION
**Pull request by blallen**
Apparently I forgot to send this earlier

### CODE REVIEW

**Comment by blallen** [comment]
I think I made the merge work, someone please check

**Comment by ali-ramadhan** [comment]
GitHub is saying "This branch has no conflicts with the base branch" so should be good to go unless there were complicated merge conflicts, in which case running a test/example might be good.

**Comment by blallen** [comment]
yeah I merged Manifest.toml manually in the github browser editor. so someone should check that :)

**Comment by ali-ramadhan** [comment]
The net effect of the merge seems to only add a valid looking entry for JLD2 to `Manifest.toml` so looks good (to me at least!).

But I don't know enough DG to review the rest of the PR haha.

**Comment by sandreza** [comment]
Looks good to me. Most of the files that were changed are the 2D stuff that takes into account all the nice changes that @blallen has made.

**Pull request merged**
